
POST  http://localhost:6000/reminder/create HTTP/1.1
Content-Type: application/json

{
    "name": "Meeting",
    "description":"I have to meet Rohan at 1 pm",
    "date":"2021-09-24T13:42:15",
    "email":"dipikesh.singh.915@gmail.com"
}

###