

GET  http://localhost:8000 HTTP/1.1

{
       
}
###
//Creating Reminder
POST  http://localhost:8000/api/reminder/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mzg2ODM2NzYsInN1YiI6IjYxYTlmZjcxYjNkNjljNTFiYjUwNWEyZiIsImlhdCI6MTYzODY4MDA3NjEwMCwiaXNzIjoiZW1haWxSZW1pbmRlci5jb20iLCJ0eXBlIjoiYXQifQ.F8SCHl1PHYwlN3vWNsHo2h2mcGAWJAZqnW72Ll56mMdE6Ht65qIOss51ZGA523f-KzvmbvadCN4gOgzMp0hZp8T9JsWpprheayH7RejWYHM-Ds-gDyie5h6eni0lioRHYD4uL_SF3FXwljFmi0aJDSg2KbkRuZCnnWNiD03s2w551RH8FqLScA4KCTPBv5PSOVTu9-zrq9XEesCM0AleH2cSdQxcmT4vOixifuc1fMYxRXhAPS1z6mangulljXcB5WbGw5aRCgo08kgKLctMkYFn9cpODDS1hP1ZkRQc4KpJGoMMD0-M3lF6MsNr7Pf5ojboPsvDtYPfcxlbhmrfwAOG_R0HFFQKdb2EjQ9tCahjip196f-AQmJSI6UvNWBqJ2rjtCszy0xU4WvwTGpZLFnCXNUjSoAAuvLb2upNOD9iiWgfP8he5O3FAYksSDXOqhPRa3RIw2eK0yNmLQwrlEdbP5PjdG-I0SerrgzP8J94_0SuF8pP8z6XRCSWJktFekWicHJsUoS2IHAdKqANBWCqdV5vVoKIsxRgmrO8rgdF_5wUzE0VJkL9cElEKyt4jW38N_ypFweahOIAQnG1h11fsgUEhALSxLxYnmS7ctopBZpvtRIa0LcERfuEreh-3iG7z_2eP5jk0lA9dzWQX1bAuK7b1c2pD0JbRhoQFqA

{
    "name": "Meeting",
    "description":"I have to meet Rohan at 1 pm",
    "date":"2021-12-05T10:27"
    
}

###
//Updating Reminder
PUT  http://localhost:8000/api/reminder/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzM4NTg3OTQsInN1YiI6IjYxNjEzMjRmMzI0YTc1M2U0ZmUyYjFjMCIsImlhdCI6MTYzMzg1NTE5NDA2MywiaXNzIjoiZW1haWxSZW1pbmRlci5jb20iLCJ0eXBlIjoiYXQifQ.G2WuCpmDLJ99tqJuKcDcUgngbN45DwIWAJwwTuZaiORiNKRYzMgGbegxqGtzjYhpVh_PEyDsBqm1RLHEayQLCWfpsPuTgwjQHOU28CiJ_ny6gBWW80oxEEM3pk6ObD0sdSQJGZ_aL-TlY8Zuio0JUhDhgjYzIMM9sH-OsIecFH4fn1kF05PI6fc_44vYQB3LG8o02xCyGNp7jIyysXQch8Mjg7zvDkTzzdqJTymj6lHbTW-aqKeFXnN1x917YjXUAcbk9F6kftpAqcggu6ZCpXsK_lzu8Zuk9uF-JAMdHv-IswWoGa80kh68zKsoePuP98u2n7hRVHruweTXZuEEfLH7YJ3fs6RWX84BdzXZ4hgNF9-nF4QlcH0NkOIrnZTrdG9LyRw5iNVNxgntwWNbMFalGzgwQK8lktTn6un-OgQa5-HHAldEOzETaRsafaGKqTdc_bhicHqVE92FXP4hglJAmQ-2-u2lC96aaaCLsaUInLCLx6gbTnRvgMNcqUUe3cE3piQukcC-s_cBItoyZQloX24eTgHlrDz2e6Tl5BqUqua5FInIJVIaRcaD3GyGVU644zlQbyJ9pN20yrfN1FlvzkUXFLxDi3fb35B53f4ein8ualP7ysvG5CShuqemrwt0t9wdOeNEVc-urmXp9Pd2B9lP7nl9TrocXwpKtXE

{
    "name": "Meeting",
    "description":"I have to meet Rohan at 1 pm",
    "date":"2021-11-06T23:22:59",
    "id":"616298c2d891834adebd07wedfsd9"
   
}
####
//Deleting Reminder
POST http://localhost:8000/api/reminder/remove HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzMzNzQ0NjgsInN1YiI6IjYxNWI0MmIwMTg3YTgyYzQ4ZDg4NjJjNiIsImlhdCI6MTYzMzM3MDg2ODA5MywiaXNzIjoiZW1haWxSZW1pbmRlci5jb20iLCJ0eXBlIjoiYXQifQ.PXuThY_OkYE4_vkY_33_Lf_PTI6-TDBlnR86otxH_idt0J2ViuymRos66Va_7wpPHLaH6RF6KmX7-vQpsPOlQOwEJVRoyOLpqrfnGRAYlUZgoBSY47cLsQFHKjnM7tyUkEKmtJ0Dzgz8WGThVHlHI3diCBclG7qUiCJ3hPBH6DlxCK61OOMR5hFNIKxjZpR6tOGSvdlSqjENfhhScyo9bpaPC3rD9nZqFW9eyi2qZOaXdmPb9fnG3b1l1kpgYSV_7GGGPcho3R-Xg4gm9B1jK0-ZhS5fod62Sehmte0GIzpJWTVB0uzWo3VMTvVO-pttuAJOJ8WWmDpUE0kK8DXOUZ0u3unb9UIO82fLhzS-rjbRZeinf9U81IYsEMU6vKvrpgCihVkmr5KyJLUQfVNfjbOw06x-k-BF3dTTy8xbYl1X2OCri_jdsomu6245r-mYA19DiTOzpVYMqTt8znpQt3NrmsBblgLhYsVCtMj3jharAJ1CNZozYrsOqz4cg45uJjcKP8c-d860J3r2muP6Ufdaa9jKQmgY6qgmt4UF0WgO3nW_ANovb-f_ucMYaEANi8dQjwNuAYOK-GcInRpvyPh8k9w7YWlhPHZ4IQbzNgniSNztNI3DJKgMRF9XJ1JxBNCQqkYzP63xNJIci6Hfqv9AgAjaAdDKwTUL1RaS4A8

{
   "id":"615b431ab60188010ea159d8"
    
}
###
//Register Users

POST http://localhost:8000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "email":"dipikeshjh@gmail.com"
 
}
###

//Confirm Register
POST http://localhost:8000/api/auth/cnfrm-register HTTP/1.1
Content-Type: application/json

{
    "name":"Dipikesh",
    "email":"dipikeshjh@gmail.com",
    "password":"Dipikesh@123",
    "cnfPassword":"Dipikesh@123",
    "otp":"9de743"
}
###
//LOGIN User
POST http://localhost:8000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"suvadeepmaity18@gmail.com",
    "password":"Suvadeep@123"
}

###
GET http://localhost:8000/api/reminder/info HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mzc4MzgwMzksInN1YiI6IjYxOTQ3ZmZjYWFmMWMyMTM0NDI1N2M1YSIsImlhdCI6MTYzNzgzNDQzOTkxMSwiaXNzIjoiZW1haWxSZW1pbmRlci5jb20iLCJ0eXBlIjoiYXQifQ.UPOk0_LXL8V2LrMe5mA31AcT0XmpcqeBUyADvD0jocsAbpvMLWAVaj7L5RcCql-DCzAJBuNVHfRkMRySOgTzYZOjgyyiog6uyO9kdGhcVytE0vVUKnmoJFbnhrx20VOzSdFS9JTBZ1rIQBKmraA7wjysA86vZhWPdn2kKdLRgzyTbLYGThBY5m6bwWUvuJd_zDbgc54Py5iqII0q9w5Li71hRpMcVpSwBg2Tk7bFu6nK00DgNIuSqzJ2Ju7LX4-wO-pWN2lY5aLlpoVCnEZwdlLXtQGT5q30AIve2IP-VargofeqQa2OYjqbLNynNfjJs79KB-Z3eO6cAETDqZ2UEGt9W0oaRT0EcQsqQCMId4Mkkn3GoKCb01hXrjENGV1Qtqymeo1WU6Z8hB3rTQmUEJlttvsh9Ue527LT7GR0DKLqAVf00SVG51PworMP3E2gdJgZYhwcury4PY1ScdKc-wDvH9cAX_mMonkxCfq-JrPvFgIf4aaNUZrdodxMJmH8KnnW_m2CZco3qFcecCBuHUbTsXUunG4a2D5E3Hgd0BJG7fRcm-PbAJjU-mK0JnG6N0zWuKh_6Dc4SLI_dW4FGIMceudUTJrqPQTvjZD3PRIjpF0y7GASGUv05SV3VD9ilUH4WwKGWZ9Gr6kOq6v6QU2W_c5l-1U6x0mlYFOcIUc

{
   
}